### ISSUE TITLE
issue with hurry.filesize version

### ISSUE THREAD

**Issue by rmdes** [oliverilp/jellyfin-torrent-downloader#2]
Trying to run this code locally and I'm getting errors when installing the requirements. 

❯ pip3 install -r requierements.txt
Requirement already satisfied: certifi>=2020.12.5 in /usr/lib/python3.9/site-packages (from -r requierements.txt (line 1)) (2021.10.8)
Requirement already satisfied: chardet>=4.0.0 in /usr/lib/python3.9/site-packages (from -r requierements.txt (line 2)) (4.0.0)
Collecting hurry.filesize==0.9
  Using cached hurry.filesize-0.9.tar.gz (2.8 kB)

WARNING: Discarding files.pythonhosted.org/packages/ee/5e/16e17bedcf54d5b618dc0771690deda77178e5c310402881c3d2d6c5f27c/hurry.filesize-0.9.tar.gz#sha256=f5368329adbef86accd3bc9490522340bb79260455ae89b1a42c10f63801b9a6 (from //pypi.org/simple/hurry-filesize/). Requested hurry.filesize==0.9 from ://files.pythonhosted.org/packages/ee/5e/16e17bedcf54d5b618dc0771690deda77178e5c310402881c3d2d6c5f27c/hurry.filesize-0.9.tar.gz#sha256=f5368329adbef86accd3bc9490522340bb79260455ae89b1a42c10f63801b9a6 (from -r requierements.txt (line 3)) has different version in metadata: '0.9'

ERROR: Could not find a version that satisfies the requirement hurry.filesize==0.9
ERROR: No matching distribution found for hurry.filesize==0.9

**Comment by oliverilp** [comment]
Weird, I just tried it on a fresh Ubuntu install and it worked without problems. But I removed the hurry.filesize dependency anyways in favor of a own solution. It should work now.
